package util;

public class Text {
    public static final String MESSAGE_MISTAKE_FULL_GARAGE = "Garaje lleno";
    public static final String WELCOME_GARAGE = "Bienvenido al garaje";
    public static final String CHOOSE_OPTION = "Escoge una de las siguientes opciones";
    public static final String NUMBER_ONE ="1";
    public static final String NUMBER_TWO ="2";
    public static final String NUMBER_THREE ="3";
    public static final String NUMBER_FOUR ="4";
    public static final String NUMBER_FIVE ="5";
    public static final String NUMBER_SIX ="6";
    public static final String NUMBER_SEVEN ="7";
    public static final String NUMBER_EIGHT ="8";
    public static final String ADD_VEHICLE = "Agregar vehículo";
    public static final String SHOW_GARAGE = "Mostrar garaje";
    public static final String FIND_CAR_HIGHER_TOP_SPEED = "Encontrar el vehículo con la mayor velocidad máxima";
    public static final String FIND_CAR_LOWER_TOP_SPEED = "Encontrar el vehículo con la menor velocidad máxima";
    public static final String SORT_CARS_BY_MAXIMUM_SPEED_HIGHEST_TO_LOWEST = "Ordenar los vehículos por velocidad máxima (mayor a menor)";
    public static final String SHOW_BLACK_OR_BLUE_CARS= "Mostrar vehículos de color NEGRO o AZUL";
    public static final String SHOW_REFERENCES_WHITE_OR_GREEN_CARS = "Mostrar las referencias de los vehículos de color BLANCO o VERDE";
    public static final String EXIT = "Salir";
    public static final String QUESTION_ADD_VEHICLE = "¿Qué vehiculo desea agregar?";
    public static final String PLANE = "Avión";
    public static final String BOAT = "Yate";
    public static final String CAR = "Carro";
    public static final String ADDING_VEHICLES = "Adicionando vehiculos";
    public static final String GOODBYE = "Gracias por utilizar nuestra aplicación";
    public static final String INVALID_OPTION = "Opción no válida";
    public static final String ADD_COLOR_VEHICLE = "Ingrese el color del vehiculo";
    public static final String ADD_REFERENCE_VEHICLE = "Ingrese la referencia del vehiculo";
    public static final String ADD_MAXIMUM_SPEED_VEHICLE = "Ingrese la velocidad máxima del vehiculo";
    public static final String ADD_INFO_PLANE = "Ingrese la información del avión";
    public static final String ADD_INFO_BOAT = "Ingrese la información del yate";
    public static final String ADD_INFO_CAR = "Ingrese la información del carro";
    public static final String ADD_MAXIMUM_ALTITUDE = "Ingrese la altitud máxima";
    public static final String ADD_MAXIMUM_WEIGHT = "Ingrese el peso máximo";
    public static final String ADD_NUMBER_GATES = "Ingrese el número de puertas";
    public static final String EXIT_OPTION_ADD = "Saliendo de la opción de agregado";
    public static final String MAXIMUM_ALTITUDE = "Altitud máxima";
    public static final String NUMBER_GATES = "Número de puertas";
    public static final String MAXIMUM_WEIGHT = "Peso máximo";
    public static final String REFERENCE = "Referencia";
    public static final String MAXIMUM_SPEED = "Velocidad máxima";
    public static final String COLOR = "Color";
    public static final String MESSAGE_MISTAKE_EMPTY_GARAGE = "El garaje esta vacio";
}
